DROP DATABASE IF EXISTS ELC_Peliculas;
CREATE DATABASE ELC_Peliculas;
USE ELC-Peliculas;

CREATE TABLE roles (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(100) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE direccion (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(100) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE actores (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(100) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE personajes (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(100) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE colecciones (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(100) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE musica (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(100) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE produccion (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(100) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE publico_recomendado (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(100) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE categoria (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(100) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE pais_residencia (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(100) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE pais_origen (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(100) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE subcategoria (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(100) NOT NULL,
	categoria_id INT UNSIGNED NOT NULL,
	PRIMARY KEY (id)
	FOREIGN KEY (categoria_id) REFERENCES categoria(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE usuarios (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(500) NOT NULL,
	apellido VARCHAR(500) NOT NULL,
	apodo VARCHAR(500) NOT NULL,
	avatar VARCHAR(500) NOT NULL,
	fecha_nacimiento DATE NOT NULL,
	sexo VARCHAR(500) NOT NULL,
	pais_id INT UNSIGNED NOT NULL,
	estado_eclesial VARCHAR(500) NOT NULL,
	email VARCHAR(500) NOT NULL,
	contrasena VARCHAR(500) NOT NULL,
	rol_id INT UNSIGNED NOT NULL,
	creado_en DATE NOT NULL,
	editado_en DATE NULL,
	borrado BOOLEAN NOT NULL DEFAULT 0,
	PRIMARY KEY (id),
	FOREIGN KEY (pais_id) REFERENCES pais_residencia(id)
	FOREIGN KEY (rol_id) REFERENCES roles(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE peliculas (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	titulo_original VARCHAR(500) NOT NULL,
	titulo_traducido VARCHAR(500) NOT NULL,
	coleccion_id INT UNSIGNED NOT NULL,
	duracion INT UNSIGNED NOT NULL AUTO_INCREMENT,
	ano_estreno INT UNSIGNED NOT NULL AUTO_INCREMENT,
	pais_origen_id VARCHAR(2) NOT NULL
	avatar VARCHAR(500) NOT NULL,
	tmdb_id INT UNSIGNED NOT NULL,
	imdb_id INT UNSIGNED NOT NULL,
	idioma_castellano BOOLEAN NOT NULL,
	color BOOLEAN NOT NULL,
	publico_recomendado_id INT UNSIGNED NOT NULL,
	categoria_id INT UNSIGNED NOT NULL,
	subcategoria_id INT UNSIGNED NOT NULL,
	sinopsis VARCHAR(500) NOT NULL,
	precuela_de INT UNSIGNED NULL,
	secuela_de INT UNSIGNED NULL,
	creada_por INT UNSIGNED NOT NULL,
	creada_en DATE NOT NULL,
	aprobada_por INT UNSIGNED NULL,
	aprobada_en DATE NULL,
	editada_por INT UNSIGNED NULL,
	editada_en DATE NULL,
	revisada_por INT UNSIGNED NULL,
	revisada_en DATE NULL,
	borrado BOOLEAN NOT NULL DEFAULT 0,
	PRIMARY KEY (id),
	FOREIGN KEY (coleccion_id) REFERENCES colecciones(id),
	FOREIGN KEY (pais_origen_id) REFERENCES pais_origen(id),
	FOREIGN KEY (publico_recomendado_id) REFERENCES publico_recomendado(id),
	FOREIGN KEY (categoria_id) REFERENCES categorias(id),
	FOREIGN KEY (subcategoria_id) REFERENCES subcategorias(id),
	FOREIGN KEY (precuela_de) REFERENCES peliculas(id),
	FOREIGN KEY (secuela_de) REFERENCES peliculas(id),
	FOREIGN KEY (creada_por) REFERENCES usuarios(id),
	FOREIGN KEY (aprobada_por) REFERENCES usuarios(id),
	FOREIGN KEY (editada_por) REFERENCES usuarios(id),
	FOREIGN KEY (revisada_por) REFERENCES usuarios(id),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE filtros_personales (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(100) NOT NULL,
	usuario_id INT UNSIGNED NOT NULL,
	campo1 VARCHAR(500),
	valor1_id INT UNSIGNED,
	campo2 VARCHAR(500),
	valor2_id INT UNSIGNED,
	campo3 VARCHAR(500),
	valor3_id INT UNSIGNED,
	campo4 VARCHAR(500),
	valor4_id INT UNSIGNED,
	palabras_clave VARCHAR(500),
	PRIMARY KEY (id)
	FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE comentarios (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	usuario_id INT UNSIGNED NOT NULL,
	pelicula_id INT UNSIGNED NOT NULL,
	comentario
	creado_en
	editado_en
	baja_en
	baja_por
	PRIMARY KEY (id)
	FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
	FOREIGN KEY (pelicula_id) REFERENCES peliculas(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE usuario-pelicula (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	usuario_id INT UNSIGNED NOT NULL,
	pelicula_id INT UNSIGNED NOT NULL,
	favorita_descartada_nulo
	vistas
	fe_valores
	entretiene
	calidad_filmica
	PRIMARY KEY (id)
	FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
	FOREIGN KEY (pelicula_id) REFERENCES peliculas(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
	
CREATE TABLE direccion-pelicula (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	director_id INT UNSIGNED NOT NULL,
	pelicula_id INT UNSIGNED NOT NULL,
	PRIMARY KEY (id)
	FOREIGN KEY (director_id) REFERENCES director(id)
	FOREIGN KEY (pelicula_id) REFERENCES peliculas(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE actor-pelicula (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	actor_id INT UNSIGNED NOT NULL,
	pelicula_id INT UNSIGNED NOT NULL,
	personaje_id
	PRIMARY KEY (id)
	FOREIGN KEY (actor_id) REFERENCES actor(id)
	FOREIGN KEY (pelicula_id) REFERENCES peliculas(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE musica-pelicula (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	musica_id INT UNSIGNED NOT NULL,
	pelicula_id INT UNSIGNED NOT NULL,
	PRIMARY KEY (id)
	FOREIGN KEY (musica_id) REFERENCES musica(id)
	FOREIGN KEY (pelicula_id) REFERENCES peliculas(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE produccion-pelicula (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	productor_id INT UNSIGNED NOT NULL,
	pelicula_id INT UNSIGNED NOT NULL,
	PRIMARY KEY (id)
	FOREIGN KEY (productor_id) REFERENCES productor(id)
	FOREIGN KEY (pelicula_id) REFERENCES peliculas(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
